package com.example.dm_helper

import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "characters")
data class Character(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    val name: String,
    val initiative: Int,
    val portrait: Int,
    val imageUrl: String? = null,
    val conditions: List<Int> = emptyList(),
    val currentHP: Int,
    val maximumHP: Int,
    val tempHP: Int,
    val perception: Int,
    val speed: Int,
    val heroPoints: Int,
    val str: Int,
    val dex: Int,
    val con: Int,
    val wis: Int,
    val `int`: Int,
    val cha: Int,
    val reflex: Int,
    val fortitude: Int,
    val will: Int,
    val ac: Int,
    val bmUsedFrom: List<Character> = emptyList(),
    val acrobatics: Int,
    val arcana: Int,
    val athletics: Int,
    val crafting: Int,
    val deception: Int,
    val diplomacy: Int,
    val intimidation: Int,
    val medicine: Int,
    val nature: Int,
    val occultism: Int,
    val performance: Int,
    val religion: Int,
    val society: Int,
    val stealth: Int,
    val survival: Int,
    val thievery: Int,

    val resistances: List<Pair<String, Int>> = emptyList(),
    val weaknesses: List<Pair<String, Int>> = emptyList(),
    val traits: List<String> = emptyList(),
    val immunities: List<String> = emptyList(),

    // Conditions
    val blinded: Boolean,
    val clumsy: Int,
    val concealed: Boolean,
    val confused: Boolean,
    val controlled: Boolean,
    val dazzled: Boolean,
    val deafened: Boolean,
    val doomed: Int,
    val drained: Int,
    val dying: Int,
    val encumbered: Boolean,
    val enfeebled: Int,
    val fascinated: Boolean,
    val fatigued: Boolean,
    val flatFooted: Boolean,
    val fleeing: Boolean,
    val frightened: Int,
    val grabbed: Boolean,
    val immobilized: Boolean,
    val invisible: Boolean,
    val paralyzed: Boolean,
    val persistentDamage: List<Pair<String, Int>> = emptyList(),
    val petrified: Boolean,
    val prone: Boolean,
    val quickened: Boolean,
    val restrained: Boolean,
    val sickened: Int,
    val slowed: Int,
    val stunned: Int,
    val stupefied: Int,
    val unconscious: Boolean,
    val wounded: Int
)